Novelis - Data Assignment - Ajinkya Mahesh Zalkikar
06/15/2022

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pickle

In [2]:
sensor = pd.read_csv(r'/content/drive/MyDrive/data/Sensor.csv')
sensorhf = pd.read_csv(r'/content/drive/MyDrive/data/Sensor_high_freq.csv')
perref = pd.read_csv(r'/content/drive/MyDrive/data/Percent_reference.csv')

In [3]:
sensor.columns

Index(['Period Code', 'Cycle ID', 'B_2', 'B_3', 'B_4', 'B_5', 'B_9', 'B_10',
       'B_14', 'B_15', 'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22',
       'B_23', 'B_24', 'B_25', 'Good/Bad', 'timestamp'],
      dtype='object')

In [4]:
sensor = sensor.rename(columns={'Period Code': 'Period','Cycle ID':'Cycle','Good/Bad':'Class'})

In [5]:
sensor.columns

Index(['Period', 'Cycle', 'B_2', 'B_3', 'B_4', 'B_5', 'B_9', 'B_10', 'B_14',
       'B_15', 'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23',
       'B_24', 'B_25', 'Class', 'timestamp'],
      dtype='object')

In [6]:
sensor.Period.unique()

array(['1', 'start', '2', 'stop', 'Missing', 'no connection', 'Bad', '3',
       'No Data', 'I/O', '4', '5', 'no response', '6', '7', nan, '8', '9',
       '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31',
       '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
       '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53',
       '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64',
       '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75',
       '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86',
       '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97',
       '98', '99', '100'], dtype=object)

In [7]:
sensor.shape

(20631, 22)

In [8]:
for col in sensor:
  sensor = sensor[sensor[col].str.contains("Missing")==False]
  sensor = sensor[sensor[col].str.contains("No Data")==False]
  sensor = sensor[sensor[col].str.contains("start")==False]
  sensor = sensor[sensor[col].str.contains("nan")==False]
  sensor = sensor[sensor[col].str.contains("no connection")==False]
  sensor = sensor[sensor[col].str.contains("Bad")==False]
  sensor = sensor[sensor[col].str.contains("I/O")==False]
  sensor = sensor[sensor[col].str.contains("no response")==False]
  sensor = sensor[sensor[col].str.contains("stop")==False]

In [9]:
sensor.shape

(13709, 22)

In [10]:
for col in sensor:
  print(sensor[col].unique())

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30'
 '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44'
 '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56' '57' '58'
 '59' '60' '61' '62' '63' '64' '65' '66' '67' '68' '69' '70' '71' '72'
 '73' '74' '75' '76' '77' '78' '79' '80' '81' '82' '83' '84' '85' '86'
 '87' '88' '89' '90' '91' '92' '93' '94' '95' '96' '97' '98' '99' '100']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '16' '17' '18'
 '19' '22' '23' '24' '26' '27' '28' '29' '31' '33' '35' '37' '38' '39'
 '45' '46' '47' '48' '49' '50' '52' '54' '55' '56' '57' '59' '60' '61'
 '62' '63' '64' '67' '69' '70' '71' '72' '73' '75' '78' '79' '84' '85'
 '86' '88' '93' '94' '96' '97' '98' '99' '100' '101' '103' '104' '106'
 '107' '108' '109' '111' '113' '115' '116' '117' '120' '121' '122' '124'
 '125' '126' '128' '130' '132' '133' '134' '135' '137' '138' '139' '140

In [11]:
df = pd.merge(sensor,sensorhf, how = 'left', on = 'timestamp')
df.shape

(13941, 29)

In [12]:
df = df.dropna()
df.shape

(13678, 29)

In [13]:
df.columns

Index(['Period', 'Cycle', 'B_2', 'B_3', 'B_4', 'B_5', 'B_9', 'B_10', 'B_14',
       'B_15', 'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_21', 'B_22', 'B_23',
       'B_24', 'B_25', 'Class', 'timestamp', 'B_6', 'B_7', 'B_8', 'B_11',
       'B_12', 'B_13', 'Percent'],
      dtype='object')

In [14]:
for col in df:
  df = df[df[col].str.contains("Missing")==False]
  df = df[df[col].str.contains("No Data")==False]
  df = df[df[col].str.contains("start")==False]
  df = df[df[col].str.contains("nan")==False]
  df = df[df[col].str.contains("no connection")==False]
  df = df[df[col].str.contains("Bad")==False]
  df = df[df[col].str.contains("I/O")==False]
  df = df[df[col].str.contains("no response")==False]
  df = df[df[col].str.contains("stop")==False]

In [15]:
df.shape

(13376, 29)

In [16]:
df = df.sort_values(by = ['Percent'])
df

Period Cycle      B_2      B_3  B_4     B_5    B_9   B_10 B_14   B_15  \
11012     81   150   0.0003   0.0005  100  518.67  14.62  21.61  1.3  47.56   
1732      13    52   0.0064  -0.0004  100  518.67  14.62  21.61  1.3  47.52   
4822      36   113  -0.0028  -0.0002  100  518.67  14.62  21.61  1.3  47.67   
10148     75    80   0.0014  -0.0002  100  518.67  14.62  21.61  1.3  47.47   
2122      16    60   -0.002   0.0001  100  518.67  14.62  21.61  1.3   47.5   
...      ...   ...      ...      ...  ...     ...    ...    ...  ...    ...   
11954     87    43        0  -0.0003  100  518.67  14.62  21.61  1.3  47.48   
10083     74   162  -0.0014  -0.0002  100  518.67  14.62  21.61  1.3  48.03   
2004      15   105  -0.0002   0.0003  100  518.67  14.62  21.61  1.3  47.41   
7836      58   133  -0.0029  -0.0001  100  518.67  14.62  21.61  1.3  47.81   
13869    100    94  -0.0028  -0.0002  100  518.67  14.62  21.61  1.3  47.62   

       ...     B_25 Class        timestamp     B_6      B_7      B_8    B_11  \
11012  ...  23.2054     0  4/26/2020 13:15  642.79  1588.82  1412.23   553.2   
1732   ...   23.267     0   3/10/2020 0:25  642.56  1594.44  1411.13  553.26   
4822   ...  23.1288     0  3/25/2020 15:40  643.57  1588.86  1414.55  552.88   
10148  ...  23.3604     0   4/22/2020 2:45  643.03  1595.21  1408.91  553.14   
2122   ...  23.3153     0  3/11/2020 22:55  642.92  1593.79   1405.9  553.03   
...    ...      ...   ...              ...     ...      ...      ...     ...   
11954  ...    23.29     0    5/1/2020 7:40  642.52   1589.2  1411.32  552.56   
10083  ...   23.073     1  4/21/2020 19:45   643.7  1604.64  1430.56  552.33   
2004   ...   23.385     0   3/11/2020 9:25  642.18  1588.27   1398.2  554.79   
7836   ...  23.1794     1   4/10/2020 0:20  643.11  1600.78  1422.72  552.71   
13869  ...  23.3167     0   5/11/2020 6:20  642.88  1589.58  1404.38  552.61   

          B_12     B_13 Percent  
11012  2388.15  9061.46    54.5  
1732    2388.1  9055.29    54.5  
4822   2388.16  9059.82    54.5  
10148  2388.11   9036.4    54.5  
2122    2388.1  9056.95    54.5  
...        ...      ...     ...  
11954  2388.12  9064.77   76.75  
10083  2388.28  9057.02   76.75  
2004   2388.02  9058.06   76.75  
7836   2388.26  9059.97   76.75  
13869  2388.11  9058.25   76.75  

[13376 rows x 29 columns]

In [17]:
perref.columns

Index(['Percent Min', 'Percent Max', 'Rotation_SPEED_SETUP', 'rolling_SETUP',
       'Coolant_SETUP', 'Airflow_SETUP', 'UW_SETUP', 'RW_SETUP'],
      dtype='object')

In [18]:
df2 = perref.sort_values(by = ['Percent Min'])
df2 = df2.rename(columns={'Percent Min':'perc_min', 'Percent Max':'perc_max'})


In [19]:
df = df.drop('timestamp',axis = 1)


In [20]:
df

Period Cycle      B_2      B_3  B_4     B_5    B_9   B_10 B_14   B_15  \
11012     81   150   0.0003   0.0005  100  518.67  14.62  21.61  1.3  47.56   
1732      13    52   0.0064  -0.0004  100  518.67  14.62  21.61  1.3  47.52   
4822      36   113  -0.0028  -0.0002  100  518.67  14.62  21.61  1.3  47.67   
10148     75    80   0.0014  -0.0002  100  518.67  14.62  21.61  1.3  47.47   
2122      16    60   -0.002   0.0001  100  518.67  14.62  21.61  1.3   47.5   
...      ...   ...      ...      ...  ...     ...    ...    ...  ...    ...   
11954     87    43        0  -0.0003  100  518.67  14.62  21.61  1.3  47.48   
10083     74   162  -0.0014  -0.0002  100  518.67  14.62  21.61  1.3  48.03   
2004      15   105  -0.0002   0.0003  100  518.67  14.62  21.61  1.3  47.41   
7836      58   133  -0.0029  -0.0001  100  518.67  14.62  21.61  1.3  47.81   
13869    100    94  -0.0028  -0.0002  100  518.67  14.62  21.61  1.3  47.62   

       ...   B_24     B_25 Class     B_6      B_7      B_8    B_11     B_12  \
11012  ...  38.78  23.2054     0  642.79  1588.82  1412.23   553.2  2388.15   
1732   ...  38.86   23.267     0  642.56  1594.44  1411.13  553.26   2388.1   
4822   ...  38.85  23.1288     0  643.57  1588.86  1414.55  552.88  2388.16   
10148  ...  38.88  23.3604     0  643.03  1595.21  1408.91  553.14  2388.11   
2122   ...  38.89  23.3153     0  642.92  1593.79   1405.9  553.03   2388.1   
...    ...    ...      ...   ...     ...      ...      ...     ...      ...   
11954  ...  38.86    23.29     0  642.52   1589.2  1411.32  552.56  2388.12   
10083  ...   38.5   23.073     1   643.7  1604.64  1430.56  552.33  2388.28   
2004   ...     39   23.385     0  642.18  1588.27   1398.2  554.79  2388.02   
7836   ...  38.62  23.1794     1  643.11  1600.78  1422.72  552.71  2388.26   
13869  ...  38.94  23.3167     0  642.88  1589.58  1404.38  552.61  2388.11   

          B_13 Percent  
11012  9061.46    54.5  
1732   9055.29    54.5  
4822   9059.82    54.5  
10148   9036.4    54.5  
2122   9056.95    54.5  
...        ...     ...  
11954  9064.77   76.75  
10083  9057.02   76.75  
2004   9058.06   76.75  
7836   9059.97   76.75  
13869  9058.25   76.75  

[13376 rows x 28 columns]

In [21]:
for col in df:
  df[col] = df[col].astype(float)

In [22]:
df.to_csv('clean.csv')
!cp clean.csv

cp: missing destination file operand after 'clean.csv'
Try 'cp --help' for more information.


In [23]:
cleandf = pd.read_csv(r'/content/drive/MyDrive/data/clean.csv')


In [24]:
cleandf

Period  Cycle     B_2     B_3  B_4     B_5    B_9   B_10  B_14   B_15  \
0          81    150  0.0003  0.0005  100  518.67  14.62  21.61   1.3  47.56   
1          13     52  0.0064 -0.0004  100  518.67  14.62  21.61   1.3  47.52   
2          36    113 -0.0028 -0.0002  100  518.67  14.62  21.61   1.3  47.67   
3          75     80  0.0014 -0.0002  100  518.67  14.62  21.61   1.3  47.47   
4          16     60 -0.0020  0.0001  100  518.67  14.62  21.61   1.3  47.50   
...       ...    ...     ...     ...  ...     ...    ...    ...   ...    ...   
10879      66     75  0.0018  0.0000  100  518.67  14.62  21.61   1.3  47.54   
10880      53      7 -0.0039  0.0000  100  518.67  14.62  21.61   1.3  47.31   
10881      41    134 -0.0012  0.0000  100  518.67  14.62  21.61   1.3  47.40   
10882      47     12  0.0023  0.0002  100  518.67  14.62  21.61   1.3  47.30   
10883      64    215 -0.0009  0.0004  100  518.67  14.62  21.61   1.3  47.81   

       ...     B_13  Percent   perc_min  perc_max  Rotation_SPEED_SETUP  \
0      ...  9061.46   54.500  54.456584  55.27548            5900.00000   
1      ...  9055.29   54.500  54.456584  55.27548            5900.00000   
2      ...  9059.82   54.500  54.456584  55.27548            5900.00000   
3      ...  9036.40   54.500  54.456584  55.27548            5900.00000   
4      ...  9056.95   54.500  54.456584  55.27548            5900.00000   
...    ...      ...      ...        ...       ...                   ...   
10879  ...  9055.93   75.625  74.928984  75.74788            5275.08473   
10880  ...  9067.56   75.625  74.928984  75.74788            5275.08473   
10881  ...  9076.82   75.625  74.928984  75.74788            5275.08473   
10882  ...  9061.05   75.625  74.928984  75.74788            5275.08473   
10883  ...  9077.18   75.625  74.928984  75.74788            5275.08473   

       rolling_SETUP  Coolant_SETUP  Airflow_SETUP     UW_SETUP    RW_SETUP  
0         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
1         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
2         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
3         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
4         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
...              ...            ...            ...          ...         ...  
10879     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10880     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10881     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10882     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10883     -34.967136      31.491333        6.84776  3552.463338  4554.16082  

[10884 rows x 36 columns]

In [25]:
cleandf = cleandf.drop('Percent',axis = 1)
cleandf = cleandf.drop('perc_min',axis = 1)
cleandf = cleandf.drop('perc_max',axis = 1)
cleandf = cleandf.drop('Cycle',axis = 1)
cleandf = cleandf.drop('Period',axis = 1)

In [26]:
cleandf

B_2     B_3  B_4     B_5    B_9   B_10  B_14   B_15    B_16  \
0      0.0003  0.0005  100  518.67  14.62  21.61   1.3  47.56  521.04   
1      0.0064 -0.0004  100  518.67  14.62  21.61   1.3  47.52  521.75   
2     -0.0028 -0.0002  100  518.67  14.62  21.61   1.3  47.67  520.64   
3      0.0014 -0.0002  100  518.67  14.62  21.61   1.3  47.47  521.66   
4     -0.0020  0.0001  100  518.67  14.62  21.61   1.3  47.50  521.40   
...       ...     ...  ...     ...    ...    ...   ...    ...     ...   
10879  0.0018  0.0000  100  518.67  14.62  21.61   1.3  47.54  520.67   
10880 -0.0039  0.0000  100  518.67  14.62  21.61   1.3  47.31  521.68   
10881 -0.0012  0.0000  100  518.67  14.62  21.61   1.3  47.40  521.78   
10882  0.0023  0.0002  100  518.67  14.62  21.61   1.3  47.30  522.16   
10883 -0.0009  0.0004  100  518.67  14.62  21.61   1.3  47.81  520.85   

          B_17  ...      B_8    B_11     B_12     B_13  Rotation_SPEED_SETUP  \
0      2388.17  ...  1412.23  553.20  2388.15  9061.46            5900.00000   
1      2388.12  ...  1411.13  553.26  2388.10  9055.29            5900.00000   
2      2388.14  ...  1414.55  552.88  2388.16  9059.82            5900.00000   
3      2388.13  ...  1408.91  553.14  2388.11  9036.40            5900.00000   
4      2388.11  ...  1405.90  553.03  2388.10  9056.95            5900.00000   
...        ...  ...      ...     ...      ...      ...                   ...   
10879  2388.11  ...  1409.56  553.05  2388.14  9055.93            5275.08473   
10880  2388.05  ...  1400.97  553.84  2388.06  9067.56            5275.08473   
10881  2388.05  ...  1404.59  553.80  2387.98  9076.82            5275.08473   
10882  2387.95  ...  1404.15  554.83  2387.99  9061.05            5275.08473   
10883  2388.10  ...  1414.45  552.99  2388.10  9077.18            5275.08473   

       rolling_SETUP  Coolant_SETUP  Airflow_SETUP     UW_SETUP    RW_SETUP  
0         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
1         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
2         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
3         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
4         -30.000000      30.000000        7.67500  3800.000000  5100.00000  
...              ...            ...            ...          ...         ...  
10879     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10880     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10881     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10882     -34.967136      31.491333        6.84776  3552.463338  4554.16082  
10883     -34.967136      31.491333        6.84776  3552.463338  4554.16082  

[10884 rows x 31 columns]

In [27]:
train = cleandf.sample(frac=0.8,random_state=57)
test = cleandf.drop(train.index)

In [28]:
x_train = train.loc[:,train.columns != 'Class']
x_test = test.loc[:,test.columns!= 'Class']
y_train = train.loc[:,'Class']
y_test = test.loc[:,'Class']

In [29]:
logreg = LogisticRegression(max_iter=10000)

In [30]:
logreg.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [31]:
logreg.classes_

array([0, 1])

In [32]:
logreg.intercept_

array([-2.82845615e-05])

In [33]:
logreg.coef_

array([[ 4.12914924e-04,  3.80399494e-05, -2.74367194e-03,
        -1.42306032e-02, -4.01124837e-04, -5.73459719e-04,
        -3.56677352e-05,  5.98520935e-01, -1.61699769e+00,
         1.08673157e-01, -8.14798332e-03,  8.33967559e-02,
        -8.23101581e-07,  3.33088766e-01, -6.55188858e-02,
        -2.74367194e-03, -3.58828190e-01, -2.10438525e-01,
         8.83191935e-01,  6.45517637e-02,  1.14931116e-01,
        -1.57968567e+00,  1.22682618e-01,  4.72133117e-02,
        -8.43382456e-05,  2.80821901e-03, -9.98627004e-02,
         8.53201267e-02,  7.54596933e-03, -7.86913923e-03]])

In [34]:
logreg.predict(x_test)

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
logreg.score(x_test,y_test)

0.9526871841984382

In [36]:
confusion_matrix(y_test,logreg.predict(x_test))

array([[1830,   43],
       [  60,  244]])

In [37]:
rf = RandomForestClassifier(n_estimators=10000,random_state=57)

In [38]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10000, random_state=57)

In [39]:
rfpred = rf.predict(x_test)

In [40]:
rf_acc = accuracy_score(y_test,rfpred)

In [41]:
rf_acc

0.9577400091869546

In [42]:
filename = '/content/drive/MyDrive/data/final_model.sav'

In [43]:
pickle.dump(logreg,open(filename,'wb'))